version: '3.2'

services:
    api:
        image: sapiologieselim/piston-api:96b7701
        container_name: piston_api
        restart: always
        privileged: true
        ports:
            - 2000:2000
        volumes:
            - ./data/piston/packages:/piston/packages
        tmpfs:
            - /tmp:exec
